name: user_repository
description: A Dart package which manages the user domain.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'
  
dependencies:
  uuid: ^3.0.7

dev_dependencies:

